# Choose tasks to be run for each language.
# Current list of tasks:
# [sentiment, qa, qa-mc, metaphor, toxicity, paraphrase, translation-en-xx, translation-xx-en, translation-id-xx, translation-xx-id, abssum, causal, nli, mp-r, pragmatic-single, pragmatic-pair, if-eval, mt-bench, kalahi-mc]
# Supported languages:
# [en, id, vi, th, ta, tl, jv, su]
# Instead of a list, use <language>: "all" to specify all tasks to be run.

seahelm:
  id: ["sentiment", "qa", "metaphor", "toxicity", "translation-en-xx", "translation-xx-en", "abssum", "causal", "nli", "mp-r", "pragmatic-single", "pragmatic-pair", "if-eval", "mt-bench"]
  vi: ["sentiment", "qa", "toxicity", "translation-en-xx", "translation-xx-en", "abssum", "causal", "nli", "if-eval", "mt-bench"]
  th: ["sentiment", "qa", "toxicity", "translation-en-xx", "translation-xx-en", "abssum", "causal", "nli", "if-eval", "mt-bench"]
  ta: ["sentiment", "qa", "translation-en-xx", "translation-xx-en", "abssum", "causal", "nli", "mp-r", "pragmatic-single", "pragmatic-pair"]
  tl: ["sentiment", "belebele-qa-mc", "toxicity", "translation-en-xx", "translation-xx-en", "abssum", "causal", "nli", "if-eval", "mt-bench", "kalahi-mc"]

seahelm_plus:
  id: ["sentiment", "qa", "metaphor", "toxicity", "translation-en-xx", "translation-xx-en", "abssum", "causal", "nli", "mp-r", "pragmatic-single", "pragmatic-pair", "if-eval", "mt-bench"]
  vi: ["sentiment", "qa", "toxicity", "translation-en-xx", "translation-xx-en", "abssum", "causal", "nli", "if-eval", "mt-bench"]
  th: ["sentiment", "qa", "toxicity", "translation-en-xx", "translation-xx-en", "abssum", "causal", "nli", "if-eval", "mt-bench"]
  ta: ["sentiment", "qa", "translation-en-xx", "translation-xx-en", "abssum", "causal", "nli", "mp-r", "pragmatic-single", "pragmatic-pair"]
  tl: ["sentiment", "belebele-qa-mc", "toxicity", "translation-en-xx", "translation-xx-en", "abssum", "causal", "nli", "if-eval", "mt-bench", "kalahi-mc"]
  jv: ["sentiment", "qa-mc", "metaphor", "translation-id-xx", "translation-xx-id", "if-eval", "mt-bench"]
  su: ["sentiment", "qa-mc", "metaphor", "translation-id-xx", "translation-xx-id", "if-eval", "mt-bench"]

translation_only:
  id: ["translation-en-xx", "translation-xx-en"]
  km: ["translation-en-xx", "translation-xx-en"]
  lo: ["translation-en-xx", "translation-xx-en"]
  my: ["translation-en-xx", "translation-xx-en"]
  ms: ["translation-en-xx", "translation-xx-en"]
  ta: ["translation-en-xx", "translation-xx-en"]
  th: ["translation-en-xx", "translation-xx-en"]
  tl: ["translation-en-xx", "translation-xx-en"]
  vi: ["translation-en-xx", "translation-xx-en"]
  zh: ["translation-en-xx", "translation-xx-en"]

nlp_classics:
  id: ["abssum", "qa", "sentiment", "nli", "causal"]
  vi: ["abssum", "qa", "sentiment", "nli", "causal"]
  th: ["abssum", "qa", "sentiment", "nli", "causal"]
  ta: ["abssum", "qa", "sentiment", "nli", "causal"]
  tl: ["abssum", "sentiment", "nli", "causal"]

nlp_sentiment_nli_casual:
  id: ["sentiment", "nli", "causal"]
  vi: ["sentiment", "nli", "causal"]
  th: ["sentiment", "nli", "causal"]
  ta: ["sentiment", "nli", "causal"]
  tl: ["sentiment", "nli", "causal"]

qa_5shot:
  id: ["qa"]
  vi: ["qa"]
  th: ["qa"]

qa_1shot:
  ta: ["qa"]

abssum_5shot:
  id: ["abssum"]

abssum_1shot:
  ta: ["abssum"]
  th: ["abssum"] 
  tl: ["abssum"]

abssum_2shot:
  vi: ["abssum"]

custom_nlg_nlu_nlr:
  en: ["nli", "abssum"]
  id: ["translation-en-xx", "translation-xx-en", "abssum", "qa", "sentiment", "nli", "causal"]
  km: ["translation-en-xx", "translation-xx-en"]
  lo: ["translation-en-xx", "translation-xx-en"]
  ms: ["translation-en-xx", "translation-xx-en"]
  my: ["translation-en-xx", "translation-xx-en"]
  th: ["translation-en-xx", "translation-xx-en", "abssum", "qa", "sentiment", "nli", "causal"]
  ta: ["translation-en-xx", "translation-xx-en", "abssum", "qa", "sentiment", "nli", "causal"]
  tl: ["translation-en-xx", "translation-xx-en", "abssum", "sentiment", "nli", "causal"]
  vi: ["translation-en-xx", "translation-xx-en", "abssum", "qa", "sentiment", "nli", "causal"]
  zh: ["nli", "abssum", "translation-en-xx", "translation-xx-en"]
  
all_tasks:
  id: "all"
  vi: "all"
  th: "all"
  ta: "all"
  tl: "all"
  jv: "all"
  su: "all"

kalahi:
  tl: ["kalahi-mc"]

batayan:
  tl: ["sentiment", "belebele-qa-mc", "toxicity", "paraphrase", "translation-en-xx", "translation-xx-en", "abssum", "causal", "nli"]
